version: "3.0"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_fam2
    ports:
      - 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork2

  app:
    build: .
    container_name: node-app_fam
    ports:
      - 3001:3001
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2
    networks:
      - mynetwork2

networks:
  mynetwork2:

volumes:
  mongo-data:
